-- CREATING A SCHOOL DATABASE

CREATE DATABASE School;
USE School;

-- CREATING TABLE Students

CREATE TABLE STUDENT (
    Roll_No INT PRIMARY KEY,
    FName VARCHAR(50) NOT NULL,
    LName VARCHAR(50),
    Marks INT NOT NULL,
    Grade CHAR(1)
);

-- CREATING TABLE FOR TEACHERS

CREATE TABLE Teachers (
    TeacherID INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50),
    Email VARCHAR(100),
    Phone VARCHAR(15),
    Department VARCHAR(100)
);

-- CREATING TABLE FOR COURSES

CREATE TABLE Courses (
    CourseID INT AUTO_INCREMENT PRIMARY KEY,
    CourseName VARCHAR(100) NOT NULL,
    Description TEXT,
    Credits INT NOT NULL CHECK (Credits > 0),
    Department VARCHAR(100)
);

-- INSERTING VALUES TO THE TABLE STUDENT

   INSERT INTO STUDENT (Roll_No, FName, LName, Marks, Grade) VALUES
(1, 'Alice','Toms', 85, 'A'),
(2, 'Bob','Miller', 78, 'B'),
(3, 'Charlie', 'Puth',92, 'A'),
(4, 'Diana', 'Spencer',65, 'C');

-- DISPLAYING ALL THE CONTENTS OF THE TABLE STUDENT

SELECT * FROM STUDENT;

-- ADDING THE COLUMN CONTACT TO THE TABLE STUDENT

ALTER TABLE STUDENT
ADD Contact VARCHAR(15);

SELECT * FROM STUDENT;	

-- REMOVING THE GRADE COLUMN FROM THE STUDENT TABLE

ALTER TABLE STUDENT
DROP COLUMN Grade;

SELECT * FROM STUDENT;

-- RENAMING THE TABLE STUDENT TO CLASSTEN

RENAME TABLE STUDENT TO CLASSTEN;

SELECT * FROM CLASSTEN;

-- DELETING ALL ROWS FROM THE TABLE CLASS TEN

TRUNCATE TABLE CLASSTEN;

SELECT * FROM CLASSTEN;

-- REMOVING THE TABLE CLASS TEN FROM THE DATABASE

DROP TABLE CLASSTEN;

USE SCHOOL;
SHOW TABLES;







